defaults:
  - data: synthetic
  - model: disrnn
  - _self_

# Global random seed by default; individual seeds for data and model can be overridden
seed: 42

# W&B logging
wandb:
  entity: AIND-disRNN  # W&B entity/team name (don't overwrite)
  dir: ${oc.env:HOME}/outputs/wandb  # Local cache for wandb files
  project: test  # Please set your own project name here!
  name: ${data.run_name_component}_${model.run_name_component}  # Consist of data and model parts


# Hydra output directories to be distributed to the wrapper capsule
job_id: 0
hydra:
  job:
    chdir: true
  run:
    # Directory for single runs, where the user provides the job id
    dir: ${oc.env:HOME}/outputs/${job_id}
  sweep:
    # Directory for multirun sweeps, where Hydra manages job ids
    dir: ${oc.env:HOME}/outputs/multirun
